ALTER TABLE models ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS max_output_tokens INTEGER;
ALTER TABLE models ADD COLUMN IF NOT EXISTS modality TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS input_modalities JSONB;
ALTER TABLE models ADD COLUMN IF NOT EXISTS output_modalities JSONB;