package provider

var opencodeGoCatalog = []OpenCodeModelSpec{
	{
		ModelID: "glm-5.1", DisplayName: "GLM 5.1",
		Description:   "GLM 5.1 via OpenCode Go subscription.",
		ContextLength: 200000, MaxOutputTokens: 131072,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "glm-5", DisplayName: "GLM 5",
		Description:   "GLM 5 via OpenCode Go subscription.",
		ContextLength: 200000, MaxOutputTokens: 131072,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "kimi-k2.6", DisplayName: "Kimi K2.6",
		Description:   "Kimi K2.6 via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "kimi-k2.5", DisplayName: "Kimi K2.5",
		Description:   "Kimi K2.5 via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "deepseek-v4-pro", DisplayName: "DeepSeek V4 Pro",
		Description:   "DeepSeek V4 Pro via OpenCode Go subscription.",
		ContextLength: 1000000, MaxOutputTokens: 384000,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "deepseek-v4-flash", DisplayName: "DeepSeek V4 Flash",
		Description:   "DeepSeek V4 Flash via OpenCode Go subscription.",
		ContextLength: 1000000, MaxOutputTokens: 384000,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "qwen3.6-plus", DisplayName: "Qwen 3.6 Plus",
		Description:   "Qwen 3.6 Plus via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "qwen3.5-plus", DisplayName: "Qwen 3.5 Plus",
		Description:   "Qwen 3.5 Plus via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "minimax-m2.7", DisplayName: "MiniMax M2.7",
		Description:   "MiniMax M2.7 via OpenCode Go subscription. Uses Anthropic /messages endpoint.",
		ContextLength: 1048576, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "minimax-m2.5", DisplayName: "MiniMax M2.5",
		Description:   "MiniMax M2.5 via OpenCode Go subscription. Uses Anthropic /messages endpoint.",
		ContextLength: 1048576, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, ToolCalling: true, StructuredOutput: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "mimo-v2-pro", DisplayName: "MiMo V2 Pro",
		Description:   "MiMo V2 Pro via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "mimo-v2-omni", DisplayName: "MiMo V2 Omni",
		Description:   "MiMo V2 Omni via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "mimo-v2.5-pro", DisplayName: "MiMo V2.5 Pro",
		Description:   "MiMo V2.5 Pro via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
	{
		ModelID: "mimo-v2.5", DisplayName: "MiMo V2.5",
		Description:   "MiMo V2.5 via OpenCode Go subscription.",
		ContextLength: 131072, MaxOutputTokens: 16384,
		Modality: "text", InputModalities: `["text"]`, OutputModalities: `["text"]`,
		Streaming: true, Reasoning: true, ToolCalling: true,
		InputPricePerMillion: 0, OutputPricePerMillion: 0,
	},
}

// GetOpenCodeGoCatalog returns the OpenCode Go model catalog.
func GetOpenCodeGoCatalog() []OpenCodeModelSpec {
	return opencodeGoCatalog
}
