package provider

var xaiCatalog = []OpenCodeModelSpec{
	// === Grok 4.20 family ===
	{
		ModelID:                      "grok-4.20-0309-reasoning",
		DisplayName:                  "Grok 4.20 Reasoning",
		Description:                  "Most truth-seeking large language model. Reasoning mode.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    true,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         200.0,
		InputPricePerMillionCacheHit: 20.0,
		OutputPricePerMillion:        600.0,
	},
	{
		ModelID:                      "grok-4.20-0309-non-reasoning",
		DisplayName:                  "Grok 4.20 Non-Reasoning",
		Description:                  "Most truth-seeking large language model. Non-reasoning mode.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    false,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         200.0,
		InputPricePerMillionCacheHit: 20.0,
		OutputPricePerMillion:        600.0,
	},
	{
		ModelID:                      "grok-4.20-multi-agent-0309",
		DisplayName:                  "Grok 4.20 Multi-Agent",
		Description:                  "Grok 4.20 multi-agent mode for autonomous tool use.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    true,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         200.0,
		InputPricePerMillionCacheHit: 20.0,
		OutputPricePerMillion:        600.0,
	},
	// === Grok 4 family ===
	{
		ModelID:                      "grok-4-0709",
		DisplayName:                  "Grok 4",
		Description:                  "Grok 4 flagship model with vision support.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    true,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         300.0,
		InputPricePerMillionCacheHit: 75.0,
		OutputPricePerMillion:        1500.0,
	},
	{
		ModelID:                      "grok-4-fast-reasoning",
		DisplayName:                  "Grok 4 Fast Reasoning",
		Description:                  "Fast Grok 4 with reasoning. Recommended for most tasks.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    true,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         20.0,
		InputPricePerMillionCacheHit: 5.0,
		OutputPricePerMillion:        50.0,
	},
	{
		ModelID:                      "grok-4-fast-non-reasoning",
		DisplayName:                  "Grok 4 Fast Non-Reasoning",
		Description:                  "Fast Grok 4 without reasoning. Cheapest for simple tasks.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    false,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         20.0,
		InputPricePerMillionCacheHit: 5.0,
		OutputPricePerMillion:        50.0,
	},
	{
		ModelID:                      "grok-4-1-fast-reasoning",
		DisplayName:                  "Grok 4.1 Fast Reasoning",
		Description:                  "Grok 4.1 fast model with reasoning.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    true,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         20.0,
		InputPricePerMillionCacheHit: 5.0,
		OutputPricePerMillion:        50.0,
	},
	{
		ModelID:                      "grok-4-1-fast-non-reasoning",
		DisplayName:                  "Grok 4.1 Fast Non-Reasoning",
		Description:                  "Grok 4.1 fast model without reasoning.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text","image"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    false,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       true,
		InputPricePerMillion:         20.0,
		InputPricePerMillionCacheHit: 5.0,
		OutputPricePerMillion:        50.0,
	},
	// === Grok 3 family ===
	{
		ModelID:                      "grok-3",
		DisplayName:                  "Grok 3",
		Description:                  "Grok 3 flagship model. Text only.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    true,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       false,
		InputPricePerMillion:         300.0,
		InputPricePerMillionCacheHit: 75.0,
		OutputPricePerMillion:        1500.0,
	},
	{
		ModelID:                      "grok-3-mini",
		DisplayName:                  "Grok 3 Mini",
		Description:                  "Grok 3 Mini for cost-efficient tasks. Text only.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    true,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       false,
		InputPricePerMillion:         30.0,
		InputPricePerMillionCacheHit: 7.5,
		OutputPricePerMillion:        50.0,
	},
	// === Grok Code ===
	{
		ModelID:                      "grok-code-fast-1",
		DisplayName:                  "Grok Code Fast",
		Description:                  "Grok code-optimized fast model. Text only. No search tool.",
		ContextLength:                131072,
		MaxOutputTokens:              16384,
		Modality:                     "text",
		InputModalities:              `["text"]`,
		OutputModalities:             `["text"]`,
		Streaming:                    true,
		Reasoning:                    false,
		ToolCalling:                  true,
		StructuredOutput:             true,
		Vision:                       false,
		InputPricePerMillion:         20.0,
		InputPricePerMillionCacheHit: 2.0,
		OutputPricePerMillion:        150.0,
	},
}

// GetXAICatalog returns the XAI model catalog.
func GetXAICatalog() []OpenCodeModelSpec {
	return xaiCatalog
}
