package db

import (
	"context"
	"fmt"
	"net/url"
	"os"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

// buildTestDBURL resolves the base TEST_DATABASE_URL, falling back to a URL
// built from the POSTGRES_* variables. The test database name is always
// "testdb" (created by docker-compose.test.yml), not POSTGRES_DB (which is the
// app database).
func buildTestDBURL() string {
	if u := os.Getenv("TEST_DATABASE_URL"); u != "" {
		return u
	}
	user := os.Getenv("POSTGRES_USER")
	pass := os.Getenv("POSTGRES_PASSWORD")
	host := os.Getenv("POSTGRES_HOST")
	if user == "" {
		user = "modelhotel"
	}
	if pass == "" {
		pass = "changeme"
	}
	switch host {
	case "", "db":
		host = "localhost" // test runs outside Docker
	}
	return fmt.Sprintf("postgres://%s:%s@%s:5433/testdb?sslmode=disable", user, pass, host)
}

// testDBName derives the database a package's tests own, from the base URL's
// database name, the package name, and TEST_DB_SHARD.
//
// The shard segment is what lets one package's tests run as several concurrent
// `go test` processes: each is handed a different TEST_DB_SHARD and therefore a
// different database, so the sequential-within-a-process assumptions every test
// here already makes still hold. Unset (the default, and every ordinary `go
// test` run) reproduces the historic name exactly, so nothing changes for a
// caller that does not opt in.
//
// Sanitised rather than validated: the value reaches a CREATE DATABASE that
// cannot be parameterised, so anything outside [a-z0-9_] is dropped instead of
// being interpolated into DDL. A shard label is generated by the test runner,
// never typed, so mangling a hostile one is better than failing the run.
func testDBName(baseDBName, pkgName string) string {
	name := baseDBName + "_" + pkgName
	shard := strings.ToLower(os.Getenv("TEST_DB_SHARD"))
	if shard == "" {
		return name
	}
	var b strings.Builder
	for _, r := range shard {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return name
	}
	return name + "_" + b.String()
}

// testDBTarget resolves the parsed maintenance URL and the per-package database
// name both entry points work against. The URL comes back parsed so the caller
// that rewrites its path does not parse it a second time.
func testDBTarget(pkgName string) (base *url.URL, dbName string, err error) {
	parsed, err := url.Parse(buildTestDBURL())
	if err != nil {
		return nil, "", fmt.Errorf("failed to parse TEST_DATABASE_URL: %w", err)
	}
	return parsed, testDBName(strings.TrimPrefix(parsed.Path, "/"), pkgName), nil
}

// terminateBackends disconnects every session on dbName except this one, so a
// DROP DATABASE is not refused by a connection an earlier run left behind.
func terminateBackends(ctx context.Context, pool *pgxpool.Pool, dbName string) {
	_, _ = pool.Exec(ctx, fmt.Sprintf(
		`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '%s' AND pid <> pg_backend_pid()`,
		dbName,
	))
}

// SetupTestDB creates an isolated test database for a specific package.
// It parses the base TEST_DATABASE_URL, appends the package name to create a
// unique database (e.g., "testdb_model"), drops any existing version, creates
// it fresh, and returns the full connection URL for the new database.
//
// This eliminates deadlocks and state pollution when multiple test packages
// run concurrently against the same PostgreSQL instance.
//
// The caller should defer a call to CleanupTestDB to drop the database after
// tests complete, though the next test run will DROP+CREATE anyway.
func SetupTestDB(pkgName string) (string, error) {
	base, newDBName, err := testDBTarget(pkgName)
	if err != nil {
		return "", err
	}

	// Connect to the "maintenance" database (the original one) to CREATE/DROP.
	ctx := context.Background()
	maintPool, err := pgxpool.New(ctx, base.String())
	if err != nil {
		return "", fmt.Errorf("failed to connect to maintenance DB: %w", err)
	}
	defer maintPool.Close()

	terminateBackends(ctx, maintPool, newDBName)

	// Drop if exists, then create fresh.
	if _, err := maintPool.Exec(ctx, fmt.Sprintf("DROP DATABASE IF EXISTS %s", newDBName)); err != nil {
		return "", fmt.Errorf("failed to drop test database %s: %w", newDBName, err)
	}
	if _, err := maintPool.Exec(ctx, fmt.Sprintf("CREATE DATABASE %s", newDBName)); err != nil {
		return "", fmt.Errorf("failed to create test database %s: %w", newDBName, err)
	}

	// Point the URL at the per-package database.
	base.Path = "/" + newDBName
	return base.String(), nil
}

// CleanupTestDB drops the per-package test database. Call this in a defer
// from TestMain after tests finish.
func CleanupTestDB(pkgName string) {
	base, newDBName, err := testDBTarget(pkgName)
	if err != nil {
		return
	}

	ctx := context.Background()
	maintPool, err := pgxpool.New(ctx, base.String())
	if err != nil {
		return
	}
	defer maintPool.Close()

	terminateBackends(ctx, maintPool, newDBName)
	_, _ = maintPool.Exec(ctx, fmt.Sprintf("DROP DATABASE IF EXISTS %s", newDBName))
}
